volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local
  gems-data:
    driver: local

services:
  db:
    container_name: db
    image: postgres:17.4
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ".:/usr/src/app"
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    container_name: redis
    image: redis:7.4.1
    volumes:
      - ".:/usr/src/app"
      - redis-data:/data
    command: redis-server
    ports:
      - "6379:6379"

  app:
    container_name: app
    build: .
    environment:
      RAILS_ENV: development
      RACK_ENV: development
    command: bundle exec puma -C ./config/puma.rb
    volumes:
      - ".:/usr/src/app"
      - gems-data:/usr/local/bundle
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis
    stdin_open: true
    env_file: .env
    tty: true
